# Generated by Django 5.1.4 on 2024-12-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('BSlotID', models.AutoField(primary_key=True, serialize=False)),
                ('SNo', models.BigIntegerField(unique=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('TimeFrom', models.TimeField(blank=True, null=True)),
                ('TimeTo', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('SlotID', models.AutoField(primary_key=True, serialize=False)),
                ('space', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('total_slots', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='user', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('SNo', models.BigIntegerField(unique=True)),
                ('VehicleType', models.CharField(blank=True, max_length=40, null=True)),
                ('VehicleNumber', models.CharField(blank=True, max_length=40, null=True)),
                ('VehicleName', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('SNo', models.BigIntegerField(unique=True)),
                ('TotalPrice', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=30, null=True)),
                ('BSlotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkeasy.bookingslot')),
            ],
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='SlotID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkeasy.slots'),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='VehicleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkeasy.vehicle'),
        ),
    ]
