# Generated by Django 5.1.4 on 2024-12-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkeasy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
