# Generated by Django 5.1.4 on 2024-12-13 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkeasy', '0004_alter_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latest_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
