# Generated by Django 5.1.4 on 2024-12-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkeasy', '0005_customuser_latest_token_alter_customuser_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latest_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
