# Generated by Django 5.1.4 on 2024-12-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkeasy', '0007_activetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_logged_in',
        ),
        migrations.DeleteModel(
            name='ActiveToken',
        ),
    ]
