# Generated by Django 5.1.4 on 2025-03-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkeasy', '0007_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='total_slots',
        ),
    ]
